import Head from 'next/head';
import { getPrimaryMenu } from '../lib/api';
import Header from '../components/Header/Header';

export default function Home({ menuItems }) {
  return (
    <>
      <Header menuItems={menuItems} />
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  );
}

export async function getStaticProps() {
  const menuItems = await getPrimaryMenu();
  return {
    props: { menuItems },
  };
}
